apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: minimal-cluster
  region: ap-south-1
  version: "1.27"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    labels:
      role: worker

addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
