apiVersion: v1
kind: Service
metadata:
  name: otel-app
  labels:
    app: otel-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: otel-app
